name: Java CI with Maven

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: list dir
        run: |
          echo "pre checkout"
          ls -la
          exit 1
          
      - uses: actions/checkout@v4

      - name: list dir after checkout
        run: |
          echo "post checkout"
          ls -la
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: list dir after package
        run: |
          echo 'list src'
          ls src/
          echo target
          ls target/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Deploy Step
        run: |
          echo "deploy steps here"
          sleep 10
          echo "deploy done :)"
